# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-30 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('is_gluten_free', models.BooleanField(default=True)),
                ('add_on_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('ingredients', models.ManyToManyField(to='pizza.Ingredient')),
            ],
            options={
                'db_table': 'pizza_pizza',
            },
        ),
    ]
